# Generated by Django 4.0.2 on 2022-02-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SettingsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Vendor Details',
            },
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('total_bill', models.FloatField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PurchaseApp.vendor')),
            ],
            options={
                'verbose_name_plural': 'Purchase Master',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField(default=0, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SettingsApp.purchaseitems')),
                ('purchase_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseApp.purchasemaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SettingsApp.unit')),
            ],
            options={
                'verbose_name_plural': 'Purchase Details',
            },
        ),
    ]
