# Generated by Django 4.0.2 on 2022-02-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PurchaseApp.issuedetails'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='PurchaseApp.purchasedetails'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quantity',
            field=models.FloatField(),
        ),
    ]
