# Generated by Django 4.0.2 on 2022-02-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0001_initial'),
        ('PurchaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedetails',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SettingsApp.purchaseitems'),
        ),
    ]
