# Generated by Django 4.0.2 on 2022-03-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0002_alter_roomdetails_category_and_more'),
        ('PurchaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedetails',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SettingsApp.purchaseitems'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SettingsApp.purchaseitems'),
        ),
    ]
