# Generated by Django 4.0.2 on 2022-02-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseApp', '0002_alter_stock_issue_alter_stock_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='PurchaseApp.issuedetails'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='PurchaseApp.purchasedetails'),
        ),
    ]
