# Generated by Django 4.0.2 on 2022-02-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0001_initial'),
        ('PurchaseApp', '0002_alter_issuedetails_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SettingsApp.purchaseitems'),
        ),
    ]
