# Generated by Django 4.0.2 on 2022-03-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SettingsApp.roomcategory'),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='room_type',
            field=models.CharField(choices=[('Twin Bed', 'Twin Bed'), ('Twin Bed', 'Couple Bed'), ('Twin Bed', 'King Bed')], max_length=255),
        ),
    ]
