# Generated by Django 4.0.2 on 2022-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0002_alter_roomdetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='room_type',
            field=models.CharField(choices=[('Twin Bed', 'Twin Bed'), ('Twin Bed', 'Couple Bed'), ('Twin Bed', 'King Bed')], max_length=255),
        ),
    ]
