# Generated by Django 4.0.2 on 2022-03-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SettingsApp', '0003_alter_roomdetails_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BooleanField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('id_type', models.CharField(max_length=100)),
                ('id_photo', models.ImageField(upload_to='')),
                ('id_no', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('days', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SalesApp.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SettingsApp.roomdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
