# Generated by Django 4.0.2 on 2022-03-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0003_alter_roomdetails_room_type'),
        ('SalesApp', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_booking', to='SettingsApp.roomdetails'),
        ),
    ]
