# Generated by Django 4.0.2 on 2022-03-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SettingsApp', '0003_alter_roomdetails_room_type'),
        ('SalesApp', '0003_alter_roombooking_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_bill', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_master', to='SalesApp.roombooking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SettingsApp.menuitems')),
                ('order_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='SalesApp.ordermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
